import NavBar from "@/component/NavBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body>
        <Providers>
          <div className="min-h-screen">
            <NavBar />
            <div className="px-8 py-6 md:px-24 py-20">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
